"""The one-week slice runner: orchestration + the auto-recap artifact.

This package is the headless heart of the M0 slice — it plays one week
(practice → match → fallout) and emits the ``recap.md`` + ``feed.snapshot.html``
artifact, with no UI and no web dependency. The Flask app in
:mod:`esports_tycoon.web` is a thin shell over it.

    from esports_tycoon.canned import loader
    from esports_tycoon.runner import SliceConfig, SliceDecisions, run_slice, write_artifacts

    world = loader.load()
    result = run_slice(world, SliceConfig(seed=6), SliceDecisions(practice_focus="defaults"))
    recap_path, feed_path, events_path = write_artifacts(result, world, "runs")
"""

from esports_tycoon.runner.engine import halftime_scoreline, run_slice, slice_id
from esports_tycoon.runner.events import (
    EVENTS_FILENAME,
    SliceEvent,
    read_events,
    slice_events,
    write_events,
)
from esports_tycoon.runner.model import (
    ANALYST_READS,
    OPEN_TEXT_MAX,
    PRACTICE_CHOICES,
    TRAINING_DRILLS,
    FeedPost,
    FollowupScrim,
    RelationshipFallout,
    ReviewRoomTrust,
    SliceConfig,
    SliceDecisions,
    SliceResult,
    TrainingConsequence,
    Week7Setup,
    normalize_open_text,
    training_decision_for_drill,
)
from esports_tycoon.runner.recap import (
    FEED_FILENAME,
    RECAP_FILENAME,
    WEEK7_SETUP_FILENAME,
    render_feed_html,
    render_recap_md,
    render_week7_setup_json,
    write_artifacts,
)
from esports_tycoon.runner.week7 import (
    WEEK7_FOCUS_FILENAME,
    WEEK7_PRESSURE_FILENAME,
    WEEK7_FOCI,
    Week7FocusLock,
    Week7FocusOption,
    Week7FocusPayload,
    Week7PressureResult,
    Week7SetupPayload,
    focus_payload_from_json,
    render_week7_focus_json,
    render_week7_pressure_json,
    resolve_week7_focus,
    resolve_week7_pressure,
    setup_payload_from_json,
    setup_payload_from_week7_setup,
    week7_focus_options,
)
from esports_tycoon.runner.week8 import (
    WEEK8_MATCH_PLAN_CHOICES,
    WEEK8_MATCH_PLAN_FILENAME,
    WEEK8_PREP_CHOICES,
    WEEK8_PREP_FILENAME,
    WEEK8_SCRIM_CHOICES,
    WEEK8_SCRIM_FILENAME,
    Week7PressurePayload,
    Week8MatchOption,
    Week8MatchPlanLock,
    Week8MatchPreview,
    Week8PrepLock,
    Week8PrepOption,
    Week8PrepPlan,
    Week8ScrimLock,
    Week8ScrimOption,
    Week8ScrimPlan,
    pressure_payload_from_json,
    render_week8_match_plan_json,
    render_week8_prep_json,
    render_week8_scrim_json,
    resolve_week8_match_plan,
    resolve_week8_prep,
    resolve_week8_scrim,
    week8_match_plan_from_json,
    week8_match_preview,
    week8_prep_from_json,
    week8_prep_plan,
    week8_scrim_from_json,
    week8_scrim_plan,
)

__all__ = [
    "run_slice",
    "slice_id",
    "halftime_scoreline",
    "SliceConfig",
    "SliceDecisions",
    "SliceResult",
    "FeedPost",
    "RelationshipFallout",
    "TrainingConsequence",
    "ReviewRoomTrust",
    "FollowupScrim",
    "Week7Setup",
    "PRACTICE_CHOICES",
    "TRAINING_DRILLS",
    "ANALYST_READS",
    "OPEN_TEXT_MAX",
    "normalize_open_text",
    "training_decision_for_drill",
    "render_recap_md",
    "render_feed_html",
    "write_artifacts",
    "RECAP_FILENAME",
    "FEED_FILENAME",
    "WEEK7_SETUP_FILENAME",
    "EVENTS_FILENAME",
    "SliceEvent",
    "slice_events",
    "read_events",
    "write_events",
    "render_week7_setup_json",
    "WEEK7_FOCUS_FILENAME",
    "WEEK7_PRESSURE_FILENAME",
    "WEEK7_FOCI",
    "Week7SetupPayload",
    "Week7FocusOption",
    "Week7FocusLock",
    "Week7FocusPayload",
    "Week7PressureResult",
    "setup_payload_from_week7_setup",
    "setup_payload_from_json",
    "focus_payload_from_json",
    "week7_focus_options",
    "resolve_week7_focus",
    "render_week7_focus_json",
    "resolve_week7_pressure",
    "render_week7_pressure_json",
    "WEEK8_PREP_FILENAME",
    "WEEK8_PREP_CHOICES",
    "WEEK8_SCRIM_FILENAME",
    "WEEK8_SCRIM_CHOICES",
    "WEEK8_MATCH_PLAN_FILENAME",
    "WEEK8_MATCH_PLAN_CHOICES",
    "Week7PressurePayload",
    "Week8PrepOption",
    "Week8PrepPlan",
    "Week8PrepLock",
    "Week8ScrimOption",
    "Week8ScrimPlan",
    "Week8ScrimLock",
    "Week8MatchOption",
    "Week8MatchPreview",
    "Week8MatchPlanLock",
    "pressure_payload_from_json",
    "week8_prep_plan",
    "resolve_week8_prep",
    "week8_prep_from_json",
    "render_week8_prep_json",
    "week8_scrim_plan",
    "resolve_week8_scrim",
    "week8_scrim_from_json",
    "render_week8_scrim_json",
    "week8_match_preview",
    "resolve_week8_match_plan",
    "week8_match_plan_from_json",
    "render_week8_match_plan_json",
]
