"""Generate DRAFT floor-plan geometry for every map.

Derives an axis-aligned rect per callout from the authored x/y anchors:
each room extends toward its neighbors, clamped so rooms don't swallow
each other. The output is a starting point meant to be hand-tuned (rooms
sized/shaped to read like the real map) — re-running OVERWRITES, so tune
in git and don't re-run casually.

Usage:
    .venv-win\\Scripts\\python.exe scripts\\gen_geometry.py [map_id ...]
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

from esports_sim.registry import load_all

OUT_DIR = Path(__file__).resolve().parents[1] / "data" / "maps" / "geometry"

MIN_SIZE = 7.0
MAX_SIZE = 18.0


def draft_regions(m) -> dict[str, dict]:
    pts = {cid: (c.x, c.y) for cid, c in m.callouts.items()}
    regions: dict[str, dict] = {}
    for cid, (x, y) in sorted(pts.items()):
        # Half-extent per side: half the distance to the nearest other
        # callout on that axis-ish, clamped. Keeps rooms roomy but disjoint.
        others = [p for oid, p in pts.items() if oid != cid]
        nearest = min(
            ((ox - x) ** 2 + (oy - y) ** 2) ** 0.5 for ox, oy in others
        )
        half = max(MIN_SIZE, min(MAX_SIZE, nearest * 0.75)) / 2.0 + MIN_SIZE / 2.0
        w = h = round(2 * half, 1)
        regions[cid] = {
            "x": round(x - w / 2, 1),
            "y": round(y - h / 2, 1),
            "w": w,
            "h": h,
        }
    return regions


def main() -> None:
    gd = load_all()
    targets = sys.argv[1:] or sorted(gd.maps)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for mid in targets:
        m = gd.maps[mid]
        doc = {
            "map_id": mid,
            "regions": draft_regions(m),
            "corridors": [],
        }
        path = OUT_DIR / f"{mid}.yaml"
        path.write_text(
            "# DRAFT geometry generated by scripts/gen_geometry.py — hand-tune.\n"
            "# Rooms are rects on the same 0-100 grid as callout x/y anchors\n"
            "# (min corner + size). Adjacent callouts whose rects touch get an\n"
            "# automatic portal; declare a corridor with via-waypoints otherwise.\n"
            + yaml.safe_dump(doc, sort_keys=True),
            encoding="utf-8",
        )
        print(f"wrote {path}")


if __name__ == "__main__":
    main()
